### ISSUE TITLE
How-to add multiple tabs?

### ISSUE THREAD

**Issue by kayazinc** [maestrith/GUI_Creator#2]
As above, I cannot seem to add multiple tabs with the latest version.

**Comment by maestrith** [comment]
Multiple tab controls or multiple tabs within one tab control?

**Comment by maestrith** [comment]
![capture](https://cloud.githubusercontent.com/assets/2114637/20996502/1e145264-bccc-11e6-8286-c6b37088a18c.gif)

**Comment by kayazinc** [comment]
Thanks @maestrith.
